name: Sync Subfolder to Hugging Face Space
on:
  schedule:
    - cron: '0 0 * * 1' # Weekly trigger
  workflow_dispatch: # Allows manual triggering for testing

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Sync Subfolder to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Navigate to the subfolder
          cd Deminiko/ct_url_breed

          # Create a temporary directory to hold the subfolder contents
          mkdir temp_dir
          cp -r * temp_dir/

          # Navigate to the temporary directory
          cd temp_dir

          # Initialize a new git repository
          git init
          git remote add origin https://huggingface.co/spaces/Deminiko/ct_url_breed

          # Add and commit all files in the subfolder
          git add .
          git commit -m "Sync subfolder from Deminiko/ct_url_breed"

          # Push the contents to the Hugging Face Space's main branch
          git push --force origin main
