- name: Sync ct_url_breed Folder to Hugging Face Space
  env:
    HF_TOKEN: ${{ secrets.HF_TOKEN }}
  run: |
    set -e  # Exit immediately if a command exits with a non-zero status

    echo "Navigating to the ct_url_breed subfolder..."
    cd Deminiko/ct_url_breed

    echo "Creating a temporary directory..."
    temp_dir=$(mktemp -d)
    echo "Temporary directory created at: $temp_dir"

    echo "Copying contents to the temporary directory..."
    cp -r ./* "$temp_dir/"

    echo "Navigating to the temporary directory..."
    cd "$temp_dir"

    echo "Initializing a new Git repository with 'main' as the default branch..."
    git init -b main

    echo "Configuring Git user information..."
    git config user.email "lluin@hotmail.com"
    git config user.name "NLarchive"

    echo "Adding Hugging Face repository as remote with authentication..."
    git remote add origin https://Deminiko:${HF_TOKEN}@huggingface.co/spaces/Deminiko/ct_url_breed.git

    echo "Fetching latest changes from the remote repository..."
    git fetch origin main

    echo "Resetting local main branch to match remote main branch..."
    git reset --soft origin/main

    echo "Adding all files to Git..."
    git add .

    echo "Committing changes..."
    git commit -m "Sync ct_url_breed folder to Hugging Face Space"

    echo "Pushing changes to Hugging Face Space on the 'main' branch..."
    git push origin main

    echo "Sync completed successfully!"
